print(format('Menu','^50'))
p_g = ('Pounds to Grams')
g_p = ('Grams to Pounds')
i_c = ('Inches to Centimerters')
c_i = ('Centimeters to Inches')
k_m = ('Kilometers to Miles')
m_k = ('Miles to Kilmeters')
print(p_g)
print(g_p)
print(i_c)
print(c_i)
print(k_m)
print(m_k)
print()
print(input('What would you like to covert today? '))
